# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Twiiter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twiiter
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
end
